feat(admin-ui): implement audit log on Services plugin
GluuFederation/gluu-admin-ui pull request #135
Opened 2021-06-03 20:04 UTC by cooldev-blue

2021-06-04 05:33 UTC, duttarnab commented
1. Ldap save not working after saving comments. Save/Update/Deleted  should work after entering comments
2. Audit logs not updated after Fetch/Save/Update/Deleted

2021-06-04 10:13 UTC, cooldev-blue commented
Corrected some features

2021-06-04 12:47 UTC, cooldev-blue commented
Merged branch 'main' into issue#134

2021-06-04 13:35 UTC, duttarnab requested changes

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/Components/Configuration/LdapAddPage.js
> +    scripts: state.ldapReducer.items,
this is a Ldap config Add page, what is the purpose of getting items from store here?

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/Components/Configuration/LdapForm.js
> +    // const [scriptTypeState, setScriptTypeState] = useState(item.scriptType)
please remove unnecessary comments from the code. I know there are already some redundant comments in code.. We should remove those.

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/redux/api/LdapApi.js
> +        console.log(data)
please remove unnecessary logs from code before check-in

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/redux/reducers/LdapReducer.js
> +reducerRegistry.register(reducerName, ldapReducer)
what is the reason for registering the reducer here? Please check how it is done for other reducers.

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/redux/sagas/LdapSaga.js
> +  console.log('==============Token ' + JSON.stringify(wholeToken))
remove unnecessary logs before check-in

2021-06-04 13:35 UTC, duttarnab commented on plugins/services-plugin/redux/actions/LdapActions.js
> +export const addLdap = (action) => ({
what is the reason of renaming `data` to `action`

2021-06-04 14:06 UTC, cooldev-blue commented on app/routes/Apps/Gluu/GluuFooter.js
> +          <Button color="primary" type="submit" className="LdapUserActionSubmitButton" style={{ visibility: 'hidden' }}>
I fixed it

2021-06-04 14:09 UTC, cooldev-blue commented on plugins/services-plugin/Components/Configuration/LdapAddPage.js
> +    scripts: state.ldapReducer.items,
No need
I removed

2021-06-04 14:10 UTC, cooldev-blue commented on plugins/services-plugin/Components/Configuration/LdapForm.js
> +    // const [scriptTypeState, setScriptTypeState] = useState(item.scriptType)
I removed unnecessary comments

2021-06-04 14:11 UTC, cooldev-blue commented on plugins/services-plugin/redux/api/LdapApi.js
> +        console.log(data)
I removed logs

2021-06-04 14:11 UTC, cooldev-blue commented on plugins/services-plugin/redux/reducers/LdapReducer.js
> +reducerRegistry.register(reducerName, ldapReducer)
I fixed it

2021-06-04 14:11 UTC, cooldev-blue commented on plugins/services-plugin/redux/sagas/LdapSaga.js
> +  console.log('==============Token ' + JSON.stringify(wholeToken))
I removed logs

2021-06-04 14:12 UTC, cooldev-blue commented on plugins/services-plugin/redux/actions/LdapActions.js
> +export const addLdap = (action) => ({
It was just renaming
I fixed it

2021-06-05 10:59 UTC, duttarnab requested changes
Ldap featch not working for branch issue#134

2021-06-06 14:40 UTC, cooldev-blue commented
now ldap page is populating records

2021-06-07 07:45 UTC, duttarnab requested changes
Please following error on console.
![image](https://user-images.githubusercontent.com/32794267/120977135-a1e09480-c790-11eb-9353-a4941df6c20c.png)

2021-06-07 09:22 UTC, cooldev-blue commented
Fixed error by changing payload parameter

2021-06-07 11:07 UTC, duttarnab approved these changes

2021-06-07 11:07 UTC, merged